package com.example.trustvault.presentation.models

import com.example.trustvault.R

enum class Platforms(val iconResId: Int) {
    GOOGLE(R.drawable.google),
    TRUSTVAULT(R.drawable.ic_trustvault),
    GMAIL(R.drawable.gmail),
    MICROSOFT(R.drawable.microsoft),
    OUTLOOK(R.drawable.outlook),
    APPLE_ID(R.drawable.apple),
    ICLOUD(R.drawable.icloud),
    FACEBOOK(R.drawable.facebook),
    INSTAGRAM(R.drawable.instagram),
    TWITTER(R.drawable.x),
    LINKEDIN(R.drawable.linkedin),
    REDDIT(R.drawable.reddit),
    YOUTUBE(R.drawable.youtube),
    AMAZON(R.drawable.amazon),
    EBAY(R.drawable.ebay),
    PAYPAL(R.drawable.paypal),
    NETFLIX(R.drawable.netflix),
    SPOTIFY(R.drawable.spotify),
    DROPBOX(R.drawable.dropbox),
    ZOOM(R.drawable.zoom),
    DISCORD(R.drawable.discord),
    TWITCH(R.drawable.twitch),
    STEAM(R.drawable.steam),
    EPIC_GAMES(R.drawable.epic_games),
    UBISOFT(R.drawable.ubisoft),
    GITHUB(R.drawable.github),
    GITLAB(R.drawable.gitlab),
    BITBUCKET(R.drawable.bitbucket),
    SLACK(R.drawable.slack),
    NOTION(R.drawable.notion),
    TRELLO(R.drawable.trello),
    ASANA(R.drawable.asana),
    OPENAI(R.drawable.chatgpt),
    ADOBE(R.drawable.adobe),
    CANVA(R.drawable.canva),
    SHOPIFY(R.drawable.shopify),
    STRIPE(R.drawable.stripe),
    AIRBNB(R.drawable.airbnb),
    UBER(R.drawable.uber),
    LYFT(R.drawable.lyft),
    PROTONMAIL(R.drawable.protonmail),
    FIGMA(R.drawable.figma),
    SAMSUNG(R.drawable.samsung),
    COURSERA(R.drawable.coursera),
    KHAN_ACADEMY(R.drawable.khan_academy),
    DUOLINGO(R.drawable.duolingo),
    STACK_OVERFLOW(R.drawable.stack_overflow),
    MEDIUM(R.drawable.medium),
    BURGERKING(R.drawable.burger_king),
    BEHANCE(R.drawable.behance),
    MEGA(R.drawable.mega)
}